Check tag format before npm deploy.

diff --git a/.github/workflows/npm_publish_on_tag_push.yml b/.github/workflows/npm_publish_on_tag_push.yml
--- a/.github/workflows/npm_publish_on_tag_push.yml
+++ b/.github/workflows/npm_publish_on_tag_push.yml
@@ -9,9 +9,26 @@ jobs:
   run_main:
     uses: ./.github/workflows/main.yml
 
+  check-version:
+    # TODO: this job should cancel the `run_main` on failure
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Compare tag with pyodide version
+        run: |
+          TAG_NAME=${GITHUB_REF#refs/tags/*}
+          TAG_VERSION="${TAG_NAME##ozobot/}"
+          PACKAGE_VERSION=$(jq -r '.version' ./src/js/package.json)
+          if [[ "$PACKAGE_VERSION" != "$TAG_VERSION" ]]
+          then
+            >&2 echo "Version derived from tag name (${TAG_NAME}) does not match version in 'src/js/package.json' file (${PACKAGE_VERSION})"
+            >&2 echo "Cancelling the deploy, as the tag and package version are out of sync."
+            exit 1
+          fi
+
   publish-npm-package:
     runs-on: ubuntu-latest
-    needs: run_main
+    needs: [check-version, run_main]
     steps:
       - uses: actions/checkout@v4
 
